package plan.app;

public class MyEnum {
	
	public enum ErrorJudgment {
		SUCCESS("1"), ERROR("0");
		private String value;
		
		ErrorJudgment(String value) {
			this.value = value;
		}
		public String getValue() {
			return value;
		}
	}
	
	public enum RoleType {
		ADMIN, USER, AWIRTER
	}
	
	public enum Region {
		INCHEON, SEOUL, BUSAN, DAEGU, ULSAN, DAEJEON, GWANGJU, SEJONG,
		GYEONGGI_DO, GANGWON_DO, CHUNGCHEONGBUK_DO, CHUNGCHEONGNAM_DO, JEOLLABUK_DO, JEOLLANAM_DO, GYEONGSANGBUK_DO, GYEONGSANGNAM_DO, JEJU,
		
		HOKKAIDO, AOMORI, IWATE, MIYAGI, AKITA, YAMAGATA, FUKUSHIMA, 
		IBARAKI, TOCHIGI, GUNMA, SAITAMA, CHIBA, TOKYO, KANAGAWA, 
		NIIGATA, TOYAMA, ISHIKAWA, FUKUI, YAMANASHI, NAGANO, KIFU, SHIZUOKA, AICHI,
		MIE, SHIGA, KYOTO, OSAKA, HYOGO, NARA, YAKAYAMA,
		TOTTORI, SHIMANE, OKAYAMA, HIROSHIMA, YAMAGUCHI, 
		TOKUSHIMA, EHIME, KOCHI, FUKUOKA, SAGA, NAGASAKI, KUMAMOTO, OITA, MIYAZAKI, KAGOSHIMA, OKINAWA,
		
		OVERSEAS
	}
	
}
